/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Dice.gltf
Author: shibi (https://sketchfab.com/shibi9966)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dice-48979fb08afc4ad8a3dd17a07c2879c9
Title: Dice
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function DiceModel(props) {
  const { nodes, materials } = useGLTF('/Dice.gltf')
  return (
    <group  scale={.5} {...props} dispose={null}>
      <mesh castShadow geometry={nodes.Object_4.geometry} material={materials['Material.003']} />
      <mesh castShadow geometry={nodes.Object_5.geometry} material={materials['Material.005']} />
    </group>
  )
}

useGLTF.preload('/Dice.gltf')
